name: CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "**" ]
jobs:
  parsing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Nix
        uses: cachix/install-nix-action@v12
      - name: Parsing
        run: 'find . -name "*.nix" -exec nix-instantiate --parse --quiet {} >/dev/null +'
        env:
          NIX_PATH: "nixpkgs=channel:nixos-20.09"
  black:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Nix
        uses: cachix/install-nix-action@v13
      - name: Black
        run: 'nix-shell ./shell.nix --run "black --check ."'
        env:
          NIX_PATH: "nixpkgs=channel:nixos-20.09"
  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Nix
        uses: cachix/install-nix-action@v13
      - name: Mypy
        run: 'nix-shell ./shell.nix --run "mypy nixops_hetzner"'
        env:
          NIX_PATH: "nixpkgs=channel:nixos-20.09"
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Nix
        uses: cachix/install-nix-action@v13
      - name: Build
        run: 'nix-build -I nixpkgs=channel:nixos-20.09 --quiet release.nix -A nixops-hetzner.x86_64-linux --show-trace'
        env:
          NIX_PATH: "nixpkgs=channel:nixos-20.09"
